<a href="https://colab.research.google.com/github/Jaewon45/ESAA-practice/blob/main/project_Classification2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data_pre = pd.read_csv("/content/drive/MyDrive/pre_full_data.csv")
data_main = pd.read_csv("/content/drive/MyDrive/main_full_data.csv")
data_end = pd.read_csv("/content/drive/MyDrive/end_full_data.csv")


In [ ]:
col = ['MESURE_AGE_CO','SEXDSTN_FLAG_CD','MESURE_IEM_001_VALUE','MESURE_IEM_002_VALUE','MESURE_IEM_003_VALUE','MESURE_IEM_005_VALUE','MESURE_IEM_006_VALUE','MESURE_IEM_012_VALUE','MESURE_IEM_018_VALUE']
data_pre_selected = data_pre[col]
data_main_selected = data_main[col]
data_end_selected = data_end[col]

# 준비운동 분류용 데이터프레임 생성
for i in range (1,11):  
  globals()['data_pre'+str(i)] = pd.concat([data_pre_selected, pd.DataFrame(data_pre.iloc[:,(i-11)])], axis=1)

# 본운동 분류용 데이터프레임 생성
for i in range (1,37):  
  globals()['data_main'+str(i)] = pd.concat([data_main_selected, pd.DataFrame(data_main.iloc[:,(i-37)])], axis=1)

# 마무리운동 분류용 데이터프레임 생성
for i in range (1,9):  
  globals()['data_end'+str(i)] = pd.concat([data_end_selected, pd.DataFrame(data_end.iloc[:,(i-9)])], axis=1)

In [ ]:
print(data_pre.shape,data_main.shape,data_end.shape)
print(data_pre_selected.shape,data_main_selected.shape,data_end_selected.shape)
print(data_pre1.shape,data_main36.shape,data_end8.shape)

(113834, 27) (113834, 53) (113834, 25)
(113834, 9) (113834, 9) (113834, 9)
(113834, 10) (113834, 10) (113834, 10)


In [ ]:
# 분류를 위한 데이터전처리용 함수 생성
def preprocessing(df):
  import pandas as pd
  from sklearn.model_selection import train_test_split
  from imblearn.over_sampling import SMOTE

  # 1) 원핫 인코딩 
  df_rev = pd.get_dummies(data=df)

  # 2) X, y 데이터로 분리 
  temp = list(range(11)); del temp[-3]
  X = df_rev.iloc[:,temp]
  X = X.astype(float)
  y = df_rev.iloc[:,-3]

  # 3) 학습/테스트용 데이터세트 분리
  
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

  # 4) SMOTE를 이용한 오버샘플링
  smote = SMOTE(random_state=42)
  X_train_over, y_train_over = smote.fit_resample(X_train, y_train)

  return (X_train, X_test, y_train, y_test, X_train_over, y_train_over)

In [ ]:
# 본운동 종류별 분류를 위한 데이터셋 생성 
X_train_main28, X_test_main28, y_train_main28, y_test_main28, X_train_over_main28, y_train_over_main28 = preprocessing(data_main28)
X_train_main29, X_test_main29, y_train_main29, y_test_main29, X_train_over_main29, y_train_over_main29 = preprocessing(data_main29)
X_train_main30, X_test_main30, y_train_main30, y_test_main30, X_train_over_main30, y_train_over_main30 = preprocessing(data_main30)
X_train_main31, X_test_main31, y_train_main31, y_test_main31, X_train_over_main31, y_train_over_main31 = preprocessing(data_main31)
X_train_main32, X_test_main32, y_train_main32, y_test_main32, X_train_over_main32, y_train_over_main32 = preprocessing(data_main32)
X_train_main33, X_test_main33, y_train_main33, y_test_main33, X_train_over_main33, y_train_over_main33 = preprocessing(data_main33)
X_train_main34, X_test_main34, y_train_main34, y_test_main34, X_train_over_main34, y_train_over_main34 = preprocessing(data_main34)
X_train_main35, X_test_main35, y_train_main35, y_test_main35, X_train_over_main35, y_train_over_main35 = preprocessing(data_main35)
X_train_main36, X_test_main36, y_train_main36, y_test_main36, X_train_over_main36, y_train_over_main36 = preprocessing(data_main36)

# 마무리운동 종류별 분류를 위한 데이터셋 생성
X_train_end5, X_test_end5, y_train_end5, y_test_end5, X_train_over_end5, y_train_over_end5 = preprocessing(data_end5)
X_train_end6, X_test_end6, y_train_end6, y_test_end6, X_train_over_end6, y_train_over_end6 = preprocessing(data_end6)
X_train_end7, X_test_end7, y_train_end7, y_test_end7, X_train_over_end7, y_train_over_end7 = preprocessing(data_end7)
X_train_end8, X_test_end8, y_train_end8, y_test_end8, X_train_over_end8, y_train_over_end8 = preprocessing(data_end8)

In [ ]:
print(X_train_main28.shape, X_test_main28.shape, y_test_main28.shape, X_train_over_main28.shape, y_train_over_main28.shape)
print(X_train_main29.shape, X_test_main29.shape, y_test_main29.shape, X_train_over_main29.shape, y_train_over_main29.shape)
print(X_train_main30.shape, X_test_main30.shape, y_test_main30.shape, X_train_over_main30.shape, y_train_over_main30.shape)
print(X_train_main31.shape, X_test_main31.shape, y_test_main31.shape, X_train_over_main31.shape, y_train_over_main31.shape)
print(X_train_main32.shape, X_test_main32.shape, y_test_main32.shape, X_train_over_main32.shape, y_train_over_main32.shape)
print(X_train_main33.shape, X_test_main33.shape, y_test_main33.shape, X_train_over_main33.shape, y_train_over_main33.shape)
print(X_train_main34.shape, X_test_main34.shape, y_test_main34.shape, X_train_over_main34.shape, y_train_over_main34.shape)
print(X_train_main35.shape, X_test_main35.shape, y_test_main35.shape, X_train_over_main35.shape, y_train_over_main35.shape)
print(X_train_main36.shape, X_test_main36.shape, y_test_main36.shape, X_train_over_main36.shape, y_train_over_main36.shape)

(79683, 10) (34151, 10) (34151,) (150182, 10) (150182,)
(79683, 10) (34151, 10) (34151,) (149692, 10) (149692,)
(79683, 10) (34151, 10) (34151,) (152002, 10) (152002,)
(79683, 10) (34151, 10) (34151,) (150410, 10) (150410,)
(79683, 10) (34151, 10) (34151,) (146440, 10) (146440,)
(79683, 10) (34151, 10) (34151,) (151468, 10) (151468,)
(79683, 10) (34151, 10) (34151,) (142498, 10) (142498,)
(79683, 10) (34151, 10) (34151,) (152506, 10) (152506,)
(79683, 10) (34151, 10) (34151,) (153340, 10) (153340,)


In [ ]:
print(X_train_end5.shape, X_test_end5.shape, y_test_end5.shape, X_train_over_end5.shape, y_train_over_end5.shape)
print(X_train_end6.shape, X_test_end6.shape, y_test_end6.shape, X_train_over_end6.shape, y_train_over_end6.shape)
print(X_train_end7.shape, X_test_end7.shape, y_test_end7.shape, X_train_over_end7.shape, y_train_over_end7.shape)
print(X_train_end8.shape, X_test_end8.shape, y_test_end8.shape, X_train_over_end8.shape, y_train_over_end8.shape)

(79683, 10) (34151, 10) (34151,) (136374, 10) (136374,)
(79683, 10) (34151, 10) (34151,) (143254, 10) (143254,)
(79683, 10) (34151, 10) (34151,) (142646, 10) (142646,)
(79683, 10) (34151, 10) (34151,) (142498, 10) (142498,)


In [43]:
## 모델 정의
# 1) RF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
myrf = RandomForestClassifier(random_state=42)

# 2) XGB
from xgboost import XGBClassifier
myxgb = XGBClassifier(random_state=42)

# 3) GBM
from lightgbm import LGBMClassifier
mylgbm = LGBMClassifier(random_state=42)


## 모델별 하이퍼파라미터튜닝용 파라미터 및 GridsearchCV 정의
from sklearn.model_selection import GridSearchCV

params_rf = { 'max_depth' : [3,4,5], 'n_estimators' : [100,150,200]}
params_xgb = { 'max_depth' : [3,4,5], 'n_estimators' : [100,150,200], 'learning_rate' : [0.1, 0.05]}
params_lgbm = { 'max_depth' : [3,4,5], 'n_estimators' : [100,150,200], 'learning_rate' : [0.1, 0.05]}

gridCV_rf = GridSearchCV(myrf, param_grid=params_rf, n_jobs=-1, cv=3, verbose=1)
gridCV_xgb = GridSearchCV(myxgb, param_grid=params_xgb, n_jobs=-1, cv=3, verbose=1)
gridCV_lgbm = GridSearchCV(mylgbm, param_grid=params_lgbm, n_jobs=-1, cv=3, verbose=1)

In [51]:
def get_clf_eval(X_train, y_train, X_test, y_test, model):
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    print(model,'=================')
    print('오차행렬')
    print(confusion)
    print('정확도 : {0:.4f}, 정밀도 : {1:.4f}, 재현율:{2:.4f}'.format(accuracy, precision, recall))

#### 본운동28

In [45]:
gridCV_rf.fit(X_train_over_main28, y_train_over_main28)
print(gridCV_rf.best_score_, gridCV_rf.best_params_)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
0.6737625125978614 {'max_depth': 5, 'n_estimators': 200}


In [46]:
gridCV_xgb.fit(X_train_over_main28, y_train_over_main28)
print(gridCV_xgb.best_score_, gridCV_xgb.best_params_)

Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9500741077507495 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


In [47]:
gridCV_lgbm.fit(X_train_over_main28, y_train_over_main28)
print(gridCV_lgbm.best_score_, gridCV_lgbm.best_params_)

Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9460057208032809 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


In [53]:
rf_main28 = RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42)
xgb_main28 = XGBClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)
lgbm_main28 = LGBMClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)

get_clf_eval(X_train_over_main28, y_train_over_main28, X_test_main28, y_test_main28, rf_main28)
get_clf_eval(X_train_over_main28, y_train_over_main28, X_test_main28, y_test_main28, xgb_main28)
get_clf_eval(X_train_over_main28, y_train_over_main28, X_test_main28, y_test_main28, lgbm_main28)

RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[14351 17742]
 [  429  1629]]
정확도 : 0.4679, 정밀도 : 0.0841, 재현율:0.7915
XGBClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[32049    44]
 [ 2050     8]]
정확도 : 0.9387, 정밀도 : 0.1538, 재현율:0.0039
LGBMClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[31865   228]
 [ 2031    27]]
정확도 : 0.9339, 정밀도 : 0.1059, 재현율:0.0131


#### 본운동 29

In [48]:
gridCV_rf.fit(X_train_over_main29, y_train_over_main29)
print(gridCV_rf.best_score_, gridCV_rf.best_params_)
gridCV_xgb.fit(X_train_over_main29, y_train_over_main29)
print(gridCV_xgb.best_score_, gridCV_xgb.best_params_)
gridCV_lgbm.fit(X_train_over_main29, y_train_over_main29)
print(gridCV_lgbm.best_score_, gridCV_lgbm.best_params_)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
0.7060631604647466 {'max_depth': 5, 'n_estimators': 100}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9418877300374904 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9362695203209505 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


In [54]:
rf_main29 = RandomForestClassifier(max_depth=5, n_estimators=100, random_state=42)
xgb_main29 = XGBClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)
lgbm_main29 = LGBMClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)

get_clf_eval(X_train_over_main29, y_train_over_main29, X_test_main29, y_test_main29, rf_main29)
get_clf_eval(X_train_over_main29, y_train_over_main29, X_test_main29, y_test_main29, xgb_main29)
get_clf_eval(X_train_over_main29, y_train_over_main29, X_test_main29, y_test_main29, lgbm_main29)

RandomForestClassifier(max_depth=5, random_state=42) =================
오차행렬
[[15471 16567]
 [  413  1700]]
정확도 : 0.5028, 정밀도 : 0.0931, 재현율:0.8045
XGBClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[31349   689]
 [ 2015    98]]
정확도 : 0.9208, 정밀도 : 0.1245, 재현율:0.0464
LGBMClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[31265   773]
 [ 1990   123]]
정확도 : 0.9191, 정밀도 : 0.1373, 재현율:0.0582


#### 본운동 30

In [49]:
gridCV_rf.fit(X_train_over_main30, y_train_over_main30)
print(gridCV_rf.best_score_, gridCV_rf.best_params_)
gridCV_xgb.fit(X_train_over_main30, y_train_over_main30)
print(gridCV_xgb.best_score_, gridCV_xgb.best_params_)
gridCV_lgbm.fit(X_train_over_main30, y_train_over_main30)
print(gridCV_lgbm.best_score_, gridCV_lgbm.best_params_)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
0.7374245043034553 {'max_depth': 5, 'n_estimators': 150}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9516390786657573 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9461457102439246 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


In [58]:
rf_main30 = RandomForestClassifier(max_depth=5, n_estimators=150, random_state=42)
xgb_main30 = XGBClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)
lgbm_main30 = LGBMClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)

get_clf_eval(X_train_over_main30, y_train_over_main30, X_test_main30, y_test_main30, rf_main30)
get_clf_eval(X_train_over_main30, y_train_over_main30, X_test_main30, y_test_main30, xgb_main30)
get_clf_eval(X_train_over_main30, y_train_over_main30, X_test_main30, y_test_main30, lgbm_main30)

RandomForestClassifier(max_depth=5, n_estimators=150, random_state=42) =================
오차행렬
[[20882 11612]
 [  400  1257]]
정확도 : 0.6483, 정밀도 : 0.0977, 재현율:0.7586
XGBClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[31701   793]
 [ 1529   128]]
정확도 : 0.9320, 정밀도 : 0.1390, 재현율:0.0772
LGBMClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[31683   811]
 [ 1533   124]]
정확도 : 0.9314, 정밀도 : 0.1326, 재현율:0.0748


#### 본운동 31

In [50]:
gridCV_rf.fit(X_train_over_main31, y_train_over_main31)
print(gridCV_rf.best_score_, gridCV_rf.best_params_)
gridCV_xgb.fit(X_train_over_main31, y_train_over_main31)
print(gridCV_xgb.best_score_, gridCV_xgb.best_params_)
gridCV_lgbm.fit(X_train_over_main31, y_train_over_main31)
print(gridCV_lgbm.best_score_, gridCV_lgbm.best_params_)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
0.71128918714215 {'max_depth': 5, 'n_estimators': 200}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9451700453888625 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9408419095340275 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


In [61]:
rf_main31 = RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42)
xgb_main31 = XGBClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)
lgbm_main31 = LGBMClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)

get_clf_eval(X_train_over_main31, y_train_over_main31, X_test_main31, y_test_main31, rf_main31)
get_clf_eval(X_train_over_main31, y_train_over_main31, X_test_main31, y_test_main31, xgb_main31)
get_clf_eval(X_train_over_main31, y_train_over_main31, X_test_main31, y_test_main31, lgbm_main31)

RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[16163 15983]
 [  363  1642]]
정확도 : 0.5214, 정밀도 : 0.0932, 재현율:0.8190
XGBClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[31188   958]
 [ 1867   138]]
정확도 : 0.9173, 정밀도 : 0.1259, 재현율:0.0688
LGBMClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[31244   902]
 [ 1883   122]]
정확도 : 0.9185, 정밀도 : 0.1191, 재현율:0.0608


#### 본운동 32

In [60]:
gridCV_rf.fit(X_train_over_main32, y_train_over_main32)
print(gridCV_rf.best_score_, gridCV_rf.best_params_)
gridCV_xgb.fit(X_train_over_main32, y_train_over_main32)
print(gridCV_xgb.best_score_, gridCV_xgb.best_params_)
gridCV_lgbm.fit(X_train_over_main32, y_train_over_main32)
print(gridCV_lgbm.best_score_, gridCV_lgbm.best_params_)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
0.7342939407790241 {'max_depth': 5, 'n_estimators': 100}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9142997758552699 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9134598479860649 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


In [62]:
rf_main32 = RandomForestClassifier(max_depth=5, n_estimators=100, random_state=42)
xgb_main32 = XGBClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)
lgbm_main32 = LGBMClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)

get_clf_eval(X_train_over_main32, y_train_over_main32, X_test_main32, y_test_main32, rf_main32)
get_clf_eval(X_train_over_main32, y_train_over_main32, X_test_main32, y_test_main32, xgb_main32)
get_clf_eval(X_train_over_main32, y_train_over_main32, X_test_main32, y_test_main32, lgbm_main32)

RandomForestClassifier(max_depth=5, random_state=42) =================
오차행렬
[[20255 11098]
 [  676  2122]]
정확도 : 0.6552, 정밀도 : 0.1605, 재현율:0.7584
XGBClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[29227  2126]
 [ 2073   725]]
정확도 : 0.8770, 정밀도 : 0.2543, 재현율:0.2591
LGBMClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[29370  1983]
 [ 2128   670]]
정확도 : 0.8796, 정밀도 : 0.2525, 재현율:0.2395


#### 본운동 33

In [63]:
gridCV_rf.fit(X_train_over_main33, y_train_over_main33)
print(gridCV_rf.best_score_, gridCV_rf.best_params_)
gridCV_xgb.fit(X_train_over_main33, y_train_over_main33)
print(gridCV_xgb.best_score_, gridCV_xgb.best_params_)
gridCV_lgbm.fit(X_train_over_main33, y_train_over_main33)
print(gridCV_lgbm.best_score_, gridCV_lgbm.best_params_)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
0.7165144133786109 {'max_depth': 5, 'n_estimators': 200}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9395848889666025 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9386209852523812 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


In [67]:
rf_main33 = RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42)
xgb_main33 = XGBClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)
lgbm_main33 = LGBMClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)

get_clf_eval(X_train_over_main33, y_train_over_main33, X_test_main33, y_test_main33, rf_main33)
get_clf_eval(X_train_over_main33, y_train_over_main33, X_test_main33, y_test_main33, xgb_main33)
get_clf_eval(X_train_over_main33, y_train_over_main33, X_test_main33, y_test_main33, lgbm_main33)

RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[19341 13058]
 [  449  1303]]
정확도 : 0.6045, 정밀도 : 0.0907, 재현율:0.7437
XGBClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[31199  1200]
 [ 1607   145]]
정확도 : 0.9178, 정밀도 : 0.1078, 재현율:0.0828
LGBMClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[31092  1307]
 [ 1586   166]]
정확도 : 0.9153, 정밀도 : 0.1127, 재현율:0.0947


#### 본운동 34

In [64]:
gridCV_rf.fit(X_train_over_main33, y_train_over_main33)
print(gridCV_rf.best_score_, gridCV_rf.best_params_)
gridCV_xgb.fit(X_train_over_main33, y_train_over_main33)
print(gridCV_xgb.best_score_, gridCV_xgb.best_params_)
gridCV_lgbm.fit(X_train_over_main33, y_train_over_main33)
print(gridCV_lgbm.best_score_, gridCV_lgbm.best_params_)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
0.7165144133786109 {'max_depth': 5, 'n_estimators': 200}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9395848889666025 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9386209852523812 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


In [68]:
rf_main34 = RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42)
xgb_main34 = XGBClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)
lgbm_main34 = LGBMClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)

get_clf_eval(X_train_over_main34, y_train_over_main34, X_test_main34, y_test_main34, rf_main34)
get_clf_eval(X_train_over_main34, y_train_over_main34, X_test_main34, y_test_main34, xgb_main34)
get_clf_eval(X_train_over_main34, y_train_over_main34, X_test_main34, y_test_main34, lgbm_main34)

RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[20657  9886]
 [  865  2743]]
정확도 : 0.6852, 정밀도 : 0.2172, 재현율:0.7603
XGBClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[27875  2668]
 [ 2200  1408]]
정확도 : 0.8575, 정밀도 : 0.3454, 재현율:0.3902
LGBMClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[27943  2600]
 [ 2244  1364]]
정확도 : 0.8582, 정밀도 : 0.3441, 재현율:0.3780


#### 본운동 35

In [65]:
gridCV_rf.fit(X_train_over_main35, y_train_over_main35)
print(gridCV_rf.best_score_, gridCV_rf.best_params_)
gridCV_xgb.fit(X_train_over_main35, y_train_over_main35)
print(gridCV_xgb.best_score_, gridCV_xgb.best_params_)
gridCV_lgbm.fit(X_train_over_main35, y_train_over_main35)
print(gridCV_lgbm.best_score_, gridCV_lgbm.best_params_)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
0.7061099475102246 {'max_depth': 5, 'n_estimators': 100}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9546315929129497 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9521070868096153 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


In [69]:
rf_main35 = RandomForestClassifier(max_depth=5, n_estimators=100, random_state=42)
xgb_main35 = XGBClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)
lgbm_main35 = LGBMClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)

get_clf_eval(X_train_over_main35, y_train_over_main35, X_test_main35, y_test_main35, rf_main35)
get_clf_eval(X_train_over_main35, y_train_over_main35, X_test_main35, y_test_main35, xgb_main35)
get_clf_eval(X_train_over_main35, y_train_over_main35, X_test_main35, y_test_main35, lgbm_main35)

RandomForestClassifier(max_depth=5, random_state=42) =================
오차행렬
[[18473 14185]
 [  451  1042]]
정확도 : 0.5714, 정밀도 : 0.0684, 재현율:0.6979
XGBClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[32135   523]
 [ 1451    42]]
정확도 : 0.9422, 정밀도 : 0.0743, 재현율:0.0281
LGBMClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[32352   306]
 [ 1465    28]]
정확도 : 0.9481, 정밀도 : 0.0838, 재현율:0.0188


#### 본운동 36

In [66]:
gridCV_rf.fit(X_train_over_main36, y_train_over_main36)
print(gridCV_rf.best_score_, gridCV_rf.best_params_)
gridCV_xgb.fit(X_train_over_main36, y_train_over_main36)
print(gridCV_xgb.best_score_, gridCV_xgb.best_params_)
gridCV_lgbm.fit(X_train_over_main36, y_train_over_main36)
print(gridCV_lgbm.best_score_, gridCV_lgbm.best_params_)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
0.708771381771227 {'max_depth': 5, 'n_estimators': 100}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9591367903797156 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.9557130347436088 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


In [70]:
rf_main36 = RandomForestClassifier(max_depth=5, n_estimators=100, random_state=42)
xgb_main36 = XGBClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)
lgbm_main36 = LGBMClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)

get_clf_eval(X_train_over_main36, y_train_over_main36, X_test_main36, y_test_main36, rf_main36)
get_clf_eval(X_train_over_main36, y_train_over_main36, X_test_main36, y_test_main36, xgb_main36)
get_clf_eval(X_train_over_main36, y_train_over_main36, X_test_main36, y_test_main36, lgbm_main36)

RandomForestClassifier(max_depth=5, random_state=42) =================
오차행렬
[[17831 15005]
 [  332   983]]
정확도 : 0.5509, 정밀도 : 0.0615, 재현율:0.7475
XGBClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[32299   537]
 [ 1257    58]]
정확도 : 0.9475, 정밀도 : 0.0975, 재현율:0.0441
LGBMClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[32387   449]
 [ 1271    44]]
정확도 : 0.9496, 정밀도 : 0.0892, 재현율:0.0335
