In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
data_pre = pd.read_csv("C:/Users/Jaewon/ESAA/newdata/pre_full_data.csv")
data_main = pd.read_csv("C:/Users/Jaewon/ESAA/newdata/main_full_data.csv")
data_end = pd.read_csv("C:/Users/Jaewon/ESAA/newdata/end_full_data.csv")


In [3]:
col = ['MESURE_AGE_CO','SEXDSTN_FLAG_CD','MESURE_IEM_001_VALUE','MESURE_IEM_002_VALUE','MESURE_IEM_003_VALUE','MESURE_IEM_005_VALUE','MESURE_IEM_006_VALUE','MESURE_IEM_012_VALUE','MESURE_IEM_018_VALUE']
data_pre_selected = data_pre[col]
data_main_selected = data_main[col]
data_end_selected = data_end[col]

# 준비운동 분류용 데이터프레임 생성
for i in range (1,11):  
  globals()['data_pre'+str(i)] = pd.concat([data_pre_selected, pd.DataFrame(data_pre.iloc[:,(i-11)])], axis=1)

# 본운동 분류용 데이터프레임 생성
for i in range (1,37):  
  globals()['data_main'+str(i)] = pd.concat([data_main_selected, pd.DataFrame(data_main.iloc[:,(i-37)])], axis=1)

# 마무리운동 분류용 데이터프레임 생성
for i in range (1,9):  
  globals()['data_end'+str(i)] = pd.concat([data_end_selected, pd.DataFrame(data_end.iloc[:,(i-9)])], axis=1)

In [4]:
print(data_pre.shape,data_main.shape,data_end.shape)
print(data_pre_selected.shape,data_main_selected.shape,data_end_selected.shape)
print(data_pre1.shape,data_main36.shape,data_end8.shape)

(113834, 27) (113834, 53) (113834, 25)
(113834, 9) (113834, 9) (113834, 9)
(113834, 10) (113834, 10) (113834, 10)


In [21]:
# 분류를 위한 데이터전처리용 함수 생성
def preprocessing(df):
    import pandas as pd
    from sklearn.model_selection import train_test_split
    from imblearn.over_sampling import SMOTE

    # 1) 원핫 인코딩 
    df_rev = pd.get_dummies(data=df)

    # 2) X, y 데이터로 분리 
    temp = list(range(11)); del temp[-3]
    X = df_rev.iloc[:,temp]
    X = X.astype(float)
    y = df_rev.iloc[:,-3]

    # 3) 학습/테스트용 데이터세트 분리
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

    # 4) SMOTE를 이용한 오버샘플링
    smote = SMOTE(random_state=42)
    X_train_over, y_train_over = smote.fit_resample(X_train, y_train)

    return (X_train, X_test, y_train, y_test, X_train_over, y_train_over)

In [22]:
# 본운동 종류별 분류를 위한 데이터셋 생성 
X_train_main28, X_test_main28, y_train_main28, y_test_main28, X_train_over_main28, y_train_over_main28 = preprocessing(data_main28)
X_train_main29, X_test_main29, y_train_main29, y_test_main29, X_train_over_main29, y_train_over_main29 = preprocessing(data_main29)
X_train_main30, X_test_main30, y_train_main30, y_test_main30, X_train_over_main30, y_train_over_main30 = preprocessing(data_main30)
X_train_main31, X_test_main31, y_train_main31, y_test_main31, X_train_over_main31, y_train_over_main31 = preprocessing(data_main31)
X_train_main32, X_test_main32, y_train_main32, y_test_main32, X_train_over_main32, y_train_over_main32 = preprocessing(data_main32)
X_train_main33, X_test_main33, y_train_main33, y_test_main33, X_train_over_main33, y_train_over_main33 = preprocessing(data_main33)
X_train_main34, X_test_main34, y_train_main34, y_test_main34, X_train_over_main34, y_train_over_main34 = preprocessing(data_main34)
X_train_main35, X_test_main35, y_train_main35, y_test_main35, X_train_over_main35, y_train_over_main35 = preprocessing(data_main35)
X_train_main36, X_test_main36, y_train_main36, y_test_main36, X_train_over_main36, y_train_over_main36 = preprocessing(data_main36)

# 마무리운동 종류별 분류를 위한 데이터셋 생성
X_train_end5, X_test_end5, y_train_end5, y_test_end5, X_train_over_end5, y_train_over_end5 = preprocessing(data_end5)
X_train_end6, X_test_end6, y_train_end6, y_test_end6, X_train_over_end6, y_train_over_end6 = preprocessing(data_end6)
X_train_end7, X_test_end7, y_train_end7, y_test_end7, X_train_over_end7, y_train_over_end7 = preprocessing(data_end7)
X_train_end8, X_test_end8, y_train_end8, y_test_end8, X_train_over_end8, y_train_over_end8 = preprocessing(data_end8)

In [8]:
print(X_train_main28.shape, X_test_main28.shape, y_test_main28.shape, X_train_over_main28.shape, y_train_over_main28.shape)
print(X_train_main29.shape, X_test_main29.shape, y_test_main29.shape, X_train_over_main29.shape, y_train_over_main29.shape)
print(X_train_main30.shape, X_test_main30.shape, y_test_main30.shape, X_train_over_main30.shape, y_train_over_main30.shape)
print(X_train_main31.shape, X_test_main31.shape, y_test_main31.shape, X_train_over_main31.shape, y_train_over_main31.shape)
print(X_train_main32.shape, X_test_main32.shape, y_test_main32.shape, X_train_over_main32.shape, y_train_over_main32.shape)
print(X_train_main33.shape, X_test_main33.shape, y_test_main33.shape, X_train_over_main33.shape, y_train_over_main33.shape)
print(X_train_main34.shape, X_test_main34.shape, y_test_main34.shape, X_train_over_main34.shape, y_train_over_main34.shape)
print(X_train_main35.shape, X_test_main35.shape, y_test_main35.shape, X_train_over_main35.shape, y_train_over_main35.shape)
print(X_train_main36.shape, X_test_main36.shape, y_test_main36.shape, X_train_over_main36.shape, y_train_over_main36.shape)

(79683, 10) (34151, 10) (34151,) (150182, 10) (150182,)
(79683, 10) (34151, 10) (34151,) (149692, 10) (149692,)
(79683, 10) (34151, 10) (34151,) (152002, 10) (152002,)
(79683, 10) (34151, 10) (34151,) (150410, 10) (150410,)
(79683, 10) (34151, 10) (34151,) (146440, 10) (146440,)
(79683, 10) (34151, 10) (34151,) (151468, 10) (151468,)
(79683, 10) (34151, 10) (34151,) (142498, 10) (142498,)
(79683, 10) (34151, 10) (34151,) (152506, 10) (152506,)
(79683, 10) (34151, 10) (34151,) (153340, 10) (153340,)


In [9]:
print(X_train_end5.shape, X_test_end5.shape, y_test_end5.shape, X_train_over_end5.shape, y_train_over_end5.shape)
print(X_train_end6.shape, X_test_end6.shape, y_test_end6.shape, X_train_over_end6.shape, y_train_over_end6.shape)
print(X_train_end7.shape, X_test_end7.shape, y_test_end7.shape, X_train_over_end7.shape, y_train_over_end7.shape)
print(X_train_end8.shape, X_test_end8.shape, y_test_end8.shape, X_train_over_end8.shape, y_train_over_end8.shape)

(79683, 10) (34151, 10) (34151,) (136374, 10) (136374,)
(79683, 10) (34151, 10) (34151,) (143254, 10) (143254,)
(79683, 10) (34151, 10) (34151,) (142646, 10) (142646,)
(79683, 10) (34151, 10) (34151,) (142498, 10) (142498,)


In [76]:
## 모델 정의
# 1) RF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
myrf = RandomForestClassifier(random_state=42)

# 2) XGB
from xgboost import XGBClassifier
myxgb = XGBClassifier(random_state=42)

# 3) GBM
from lightgbm import LGBMClassifier
mylgbm = LGBMClassifier(random_state=42)


## 모델별 하이퍼파라미터튜닝용 파라미터 및 GridsearchCV 정의
from sklearn.model_selection import GridSearchCV

params_rf = { 'max_depth' : [3,4,5], 'n_estimators' : [100,150,200]}
params_xgb = { 'max_depth' : [3,4,5], 'n_estimators' : [100,150,200], 'learning_rate' : [0.1, 0.05]}
params_lgbm = { 'max_depth' : [3,4,5], 'n_estimators' : [100,150,200], 'learning_rate' : [0.1, 0.05]}

gridCV_rf = GridSearchCV(myrf, param_grid=params_rf, cv=3, n_jobs=-1, verbose=1)
gridCV_xgb = GridSearchCV(myxgb, param_grid=params_xgb, cv=3, n_jobs=-1, verbose=1)
gridCV_lgbm = GridSearchCV(mylgbm, param_grid=params_lgbm, cv=3, n_jobs=-1, verbose=1)

In [60]:
def get_clf_eval(X_train, y_train, X_test, y_test, model):
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    print(model,'=================')
    print('오차행렬')
    print(confusion)
    print('정확도 : {0:.4f}, 정밀도 : {1:.4f}, 재현율:{2:.4f}'.format(accuracy, precision, recall))

#### 마무리운동 5

In [77]:
gridCV_rf.fit(X_train_over_end5, y_train_over_end5)
print(gridCV_rf.best_score_, gridCV_rf.best_params_)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
0.6818675114024667 {'max_depth': 5, 'n_estimators': 100}


In [79]:
gridCV_xgb.fit(X_train_over_end5, y_train_over_end5)
print(gridCV_xgb.best_score_, gridCV_xgb.best_params_)

Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.1070704164985566 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


In [80]:
gridCV_lgbm.fit(X_train_over_end5, y_train_over_end5)
print(gridCV_lgbm.best_score_, gridCV_lgbm.best_params_)

Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.09448060106672414 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


In [90]:
rf_end5 = RandomForestClassifier(max_depth=5, n_estimators=100, random_state=42)
xgb_end5 = XGBClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)
lgbm_end5 = LGBMClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)

get_clf_eval(X_train_over_end5, y_train_over_end5, X_test_end5, y_test_end5, rf_end5)
get_clf_eval(X_train_over_end5, y_train_over_end5, X_test_end5, y_test_end5, xgb_end5)
get_clf_eval(X_train_over_end5, y_train_over_end5, X_test_end5, y_test_end5, lgbm_end5)

RandomForestClassifier(max_depth=5, random_state=42) =================
오차행렬
[[17822 11472]
 [ 1765  3092]]
정확도 : 0.6124, 정밀도 : 0.2123, 재현율:0.6366
[14:12:47] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.1, max_delta_step=0,
              max_depth=5, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=200, n_jobs=4,
              num_parallel_tree=1, predictor='auto', random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, 

#### 마무리운동 6

In [81]:
gridCV_rf.fit(X_train_over_end6, y_train_over_end6)
print(gridCV_rf.best_score_, gridCV_rf.best_params_)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
0.7018373142846102 {'max_depth': 5, 'n_estimators': 200}


In [82]:
gridCV_xgb.fit(X_train_over_end6, y_train_over_end6)
print(gridCV_xgb.best_score_, gridCV_xgb.best_params_)

Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.07860001261834355 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


In [83]:
gridCV_lgbm.fit(X_train_over_end6, y_train_over_end6)
print(gridCV_lgbm.best_score_, gridCV_lgbm.best_params_)

Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.05400417249218318 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


In [91]:
rf_end6 = RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42)
xgb_end6 = XGBClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)
lgbm_end6 = LGBMClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)

get_clf_eval(X_train_over_end6, y_train_over_end6, X_test_end6, y_test_end6, rf_end6)
get_clf_eval(X_train_over_end6, y_train_over_end6, X_test_end6, y_test_end6, xgb_end6)
get_clf_eval(X_train_over_end6, y_train_over_end6, X_test_end6, y_test_end6, lgbm_end6)

RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[20352 10372]
 [ 1098  2329]]
정확도 : 0.6641, 정밀도 : 0.1834, 재현율:0.6796
[14:13:42] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.1, max_delta_step=0,
              max_depth=5, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=200, n_jobs=4,
              num_parallel_tree=1, predictor='auto', random_state=42,
              reg_alpha=0, reg_lambda=1, sc

#### 마무리운동 7

In [84]:
gridCV_rf.fit(X_train_over_end7, y_train_over_end7)
print(gridCV_rf.best_score_, gridCV_rf.best_params_)
gridCV_xgb.fit(X_train_over_end7, y_train_over_end7)
print(gridCV_xgb.best_score_, gridCV_xgb.best_params_)
gridCV_lgbm.fit(X_train_over_end7, y_train_over_end7)
print(gridCV_lgbm.best_score_, gridCV_lgbm.best_params_)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
0.7031953815832249 {'max_depth': 5, 'n_estimators': 150}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.06387078032154588 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.06099474199569377 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


In [92]:
rf_end7 = RandomForestClassifier(max_depth=5, n_estimators=150, random_state=42)
xgb_end7 = XGBClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)
lgbm_end7 = LGBMClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)

get_clf_eval(X_train_over_end7, y_train_over_end7, X_test_end7, y_test_end7, rf_end7)
get_clf_eval(X_train_over_end7, y_train_over_end7, X_test_end7, y_test_end7, xgb_end7)
get_clf_eval(X_train_over_end7, y_train_over_end7, X_test_end7, y_test_end7, lgbm_end7)

RandomForestClassifier(max_depth=5, n_estimators=150, random_state=42) =================
오차행렬
[[15957 14538]
 [  848  2808]]
정확도 : 0.5495, 정밀도 : 0.1619, 재현율:0.7681
[14:14:29] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.1, max_delta_step=0,
              max_depth=5, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=200, n_jobs=4,
              num_parallel_tree=1, predictor='auto', random_state=42,
              reg_alpha=0, reg_lambda=1, sc

In [102]:
rf_end7_rev = RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42)
get_clf_eval(X_train_over_end7, y_train_over_end7, X_test_end7, y_test_end7, rf_end7_rev)

RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[16062 14433]
 [  864  2792]]
정확도 : 0.5521, 정밀도 : 0.1621, 재현율:0.7637


In [103]:
rf_end7_rev1 = RandomForestClassifier(max_depth=5, n_estimators=400, random_state=42)
get_clf_eval(X_train_over_end7, y_train_over_end7, X_test_end7, y_test_end7, rf_end7_rev1)

RandomForestClassifier(max_depth=5, n_estimators=400, random_state=42) =================
오차행렬
[[16086 14409]
 [  862  2794]]
정확도 : 0.5528, 정밀도 : 0.1624, 재현율:0.7642


In [105]:
rf_end7_rev2 = RandomForestClassifier(max_depth=6, n_estimators=400, random_state=42)
get_clf_eval(X_train_over_end7, y_train_over_end7, X_test_end7, y_test_end7, rf_end7_rev2)

RandomForestClassifier(max_depth=6, n_estimators=400, random_state=42) =================
오차행렬
[[16919 13576]
 [  916  2740]]
정확도 : 0.5756, 정밀도 : 0.1679, 재현율:0.7495


In [106]:
rf_end7_rev3 = RandomForestClassifier(max_depth=7, n_estimators=400, random_state=42)
get_clf_eval(X_train_over_end7, y_train_over_end7, X_test_end7, y_test_end7, rf_end7_rev3)

RandomForestClassifier(max_depth=7, n_estimators=400, random_state=42) =================
오차행렬
[[18350 12145]
 [ 1071  2585]]
정확도 : 0.6130, 정밀도 : 0.1755, 재현율:0.7071


#### 마무리운동 8

In [85]:
gridCV_rf.fit(X_train_over_end8, y_train_over_end8)
print(gridCV_rf.best_score_, gridCV_rf.best_params_)
gridCV_xgb.fit(X_train_over_end8, y_train_over_end8)
print(gridCV_xgb.best_score_, gridCV_xgb.best_params_)
gridCV_lgbm.fit(X_train_over_end8, y_train_over_end8)
print(gridCV_lgbm.best_score_, gridCV_lgbm.best_params_)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
0.7463192730557946 {'max_depth': 5, 'n_estimators': 200}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.10949634425159467 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}
Fitting 3 folds for each of 18 candidates, totalling 54 fits
0.09784785073923392 {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}


In [93]:
rf_end8 = RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42)
xgb_end8 = XGBClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)
lgbm_end8 = LGBMClassifier(learning_rate=0.1, max_depth=5, n_estimators=200, random_state=42)

get_clf_eval(X_train_over_end8, y_train_over_end8, X_test_end8, y_test_end8, rf_end8)
get_clf_eval(X_train_over_end8, y_train_over_end8, X_test_end8, y_test_end8, xgb_end8)
get_clf_eval(X_train_over_end8, y_train_over_end8, X_test_end8, y_test_end8, lgbm_end8)

RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42) =================
오차행렬
[[20635  9908]
 [  865  2743]]
정확도 : 0.6845, 정밀도 : 0.2168, 재현율:0.7603
[14:16:18] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.1, max_delta_step=0,
              max_depth=5, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=200, n_jobs=4,
              num_parallel_tree=1, predictor='auto', random_state=42,
              reg_alpha=0, reg_lambda=1, sc

In [100]:
rf_end8_rev = RandomForestClassifier(max_depth=5, n_estimators=400, random_state=42)
get_clf_eval(X_train_over_end8, y_train_over_end8, X_test_end8, y_test_end8, rf_end8_rev)

RandomForestClassifier(max_depth=5, n_estimators=400, random_state=42) =================
오차행렬
[[20652  9891]
 [  862  2746]]
정확도 : 0.6851, 정밀도 : 0.2173, 재현율:0.7611


In [98]:
rf_end8_rev1 = RandomForestClassifier(max_depth=5, n_estimators=600, random_state=42)
get_clf_eval(X_train_over_end8, y_train_over_end8, X_test_end8, y_test_end8, rf_end8_rev1)

RandomForestClassifier(max_depth=5, n_estimators=600, random_state=42) =================
오차행렬
[[20619  9924]
 [  862  2746]]
정확도 : 0.6842, 정밀도 : 0.2167, 재현율:0.7611


In [96]:
rf_end8_rev2 = RandomForestClassifier(max_depth=6, n_estimators=400, random_state=42)
get_clf_eval(X_train_over_end8, y_train_over_end8, X_test_end8, y_test_end8, rf_end8_rev2)

RandomForestClassifier(max_depth=6, n_estimators=400, random_state=42) =================
오차행렬
[[21470  9073]
 [  920  2688]]
정확도 : 0.7074, 정밀도 : 0.2286, 재현율:0.7450


In [95]:
rf_end8_rev3 = RandomForestClassifier(max_depth=7, n_estimators=400, random_state=42)
get_clf_eval(X_train_over_end8, y_train_over_end8, X_test_end8, y_test_end8, rf_end8_rev3)

RandomForestClassifier(max_depth=7, n_estimators=400, random_state=42) =================
오차행렬
[[22241  8302]
 [  978  2630]]
정확도 : 0.7283, 정밀도 : 0.2406, 재현율:0.7289


In [99]:
rf_end8_rev4 = RandomForestClassifier(max_depth=5, n_estimators=100, random_state=42)
get_clf_eval(X_train_over_end8, y_train_over_end8, X_test_end8, y_test_end8, rf_end8_rev4)

RandomForestClassifier(max_depth=5, random_state=42) =================
오차행렬
[[20506 10037]
 [  846  2762]]
정확도 : 0.6813, 정밀도 : 0.2158, 재현율:0.7655
